"""Generate every Quapp logo asset from one spec (DESIGN.md section 8).

The mark is an espresso ticket on a 40 x 50 grid: corner radius 5, half-circle punches (r 3.4) on
both sides at y 36, a crema tear line across at y 36, and a cream DM Serif Display Q
(size 28, centred, baseline 26.5).

Outputs (run from the repo root:  python tools/make_logo.py):
  res/drawable/ic_quapp_mark.xml              full-colour mark (splash, lockups)
  res/drawable/ic_launcher_foreground.xml     adaptive icon foreground (mark in the 66dp safe zone)
  res/drawable/ic_launcher_monochrome.xml     themed-icon layer (Android 13+), one colour
  res/drawable/ic_stat_quapp.xml              notification small icon, one-colour cut-out
  res/mipmap-*/ic_launcher(.webp, _round.webp) raster icons for Android 7.x (API 24-25)

Vector drawables can't draw text, so the Q is the glyph's real outline read from the font file.
"""
import os
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, 'app', 'src', 'main', 'res')
FONT = os.path.join(RES, 'font', 'dm_serif_display.ttf')

# The spec
W, H, R = 40, 50, 5
PUNCH_Y, PUNCH_R = 36, 3.4
TEAR_X0, TEAR_X1, TEAR_W, DASH, GAP = 6.5, 33.5, 1.3, 2, 2
Q_SIZE, Q_BASELINE = 28, 26.5
ESPRESSO, CREAM, CREMA, PAPER = '#2B211C', '#F6EFE6', '#C8A27A', '#F2EDE3'


def ticket_path():
    """Rounded rectangle with a half-circle bitten out of each side at PUNCH_Y."""
    t, b = PUNCH_Y - PUNCH_R, PUNCH_Y + PUNCH_R
    return (f'M{R},0 H{W - R} A{R},{R} 0 0 1 {W},{R} '
            f'V{t:g} A{PUNCH_R},{PUNCH_R} 0 0 0 {W},{b:g} '          # right punch, bites inward
            f'V{H - R} A{R},{R} 0 0 1 {W - R},{H} H{R} A{R},{R} 0 0 1 0,{H - R} '
            f'V{b:g} A{PUNCH_R},{PUNCH_R} 0 0 0 0,{t:g} '            # left punch, bites inward
            f'V{R} A{R},{R} 0 0 1 {R},0 Z')


def dashes():
    """The tear line as small rectangles (vector drawables have no dashed strokes)."""
    out, x, y0 = [], TEAR_X0, PUNCH_Y - TEAR_W / 2
    while x + DASH <= TEAR_X1 + 0.01:
        out.append(f'M{x:g},{y0:g} h{DASH} v{TEAR_W} h-{DASH} Z')
        x += DASH + GAP
    return ' '.join(out)


def q_path():
    font = TTFont(FONT)
    glyphs = font.getGlyphSet()
    name = font.getBestCmap()[ord('Q')]
    s = Q_SIZE / font['head'].unitsPerEm
    advance = font['hmtx'][name][0] * s
    pen = SVGPathPen(glyphs, ntos=lambda v: f'{v:.2f}'.rstrip('0').rstrip('.'))
    # font units are y-up; flip, scale and centre on x = W/2 with the baseline at Q_BASELINE
    glyphs[name].draw(TransformPen(pen, (s, 0, 0, -s, W / 2 - advance / 2, Q_BASELINE)))
    return pen.getCommands()


def vector(name, body, width, height, vw=W, vh=H, comment=''):
    xml = ('<?xml version="1.0" encoding="utf-8"?>\n'
           f'<!-- Generated by tools/make_logo.py. {comment} Edit the script, not this file. -->\n'
           '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
           f'    android:width="{width}dp"\n    android:height="{height}dp"\n'
           f'    android:viewportWidth="{vw}"\n    android:viewportHeight="{vh}">\n{body}</vector>\n')
    with open(os.path.join(RES, 'drawable', name), 'w', encoding='utf-8', newline='\n') as f:
        f.write(xml)


def full_mark_paths(indent='    '):
    return (f'{indent}<path android:fillColor="@color/spotlight" android:pathData="{ticket_path()}" />\n'
            f'{indent}<path android:fillColor="@color/crema" android:pathData="{dashes()}" />\n'
            f'{indent}<path android:fillColor="@color/on_spotlight" android:pathData="{q_path()}" />\n')


def cutout_path(indent='    ', color='#FFFFFFFF'):
    # evenOdd: the Q's outline becomes a hole in the ticket; its counter (the bowl's inside) fills again
    return (f'{indent}<path android:fillColor="{color}" android:fillType="evenOdd"\n'
            f'{indent}    android:pathData="{ticket_path()} {q_path()}" />\n')


def group(inner, scale, tx, ty):
    return (f'    <group android:scaleX="{scale}" android:scaleY="{scale}" '
            f'android:translateX="{tx}" android:translateY="{ty}">\n{inner}    </group>\n')


def raster(size, round_icon):
    """Legacy launcher icon for API 24-25: paper tile with the mark, drawn at 4x then scaled down."""
    k = size * 4 / 108                       # same geometry as the adaptive icon's 108dp canvas
    img = Image.new('RGBA', (size * 4, size * 4), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    if round_icon:
        d.ellipse([0, 0, size * 4 - 1, size * 4 - 1], fill=PAPER)
    else:
        d.rounded_rectangle([0, 0, size * 4 - 1, size * 4 - 1], radius=int(size * 4 * .2), fill=PAPER)
    m = 1.25 * k                             # mark scale inside the 108 canvas (a bit larger than adaptive: no mask)
    ox, oy = (size * 4 - W * m) / 2, (size * 4 - H * m) / 2
    d.rounded_rectangle([ox, oy, ox + W * m, oy + H * m], radius=R * m, fill=ESPRESSO)
    for cx in (ox, ox + W * m):
        d.ellipse([cx - PUNCH_R * m, oy + (PUNCH_Y - PUNCH_R) * m, cx + PUNCH_R * m, oy + (PUNCH_Y + PUNCH_R) * m], fill=PAPER)
    x = TEAR_X0
    while x + DASH <= TEAR_X1 + 0.01:
        d.rectangle([ox + x * m, oy + (PUNCH_Y - TEAR_W / 2) * m, ox + (x + DASH) * m, oy + (PUNCH_Y + TEAR_W / 2) * m], fill=CREMA)
        x += DASH + GAP
    font = ImageFont.truetype(FONT, int(Q_SIZE * m))
    d.text((ox + W / 2 * m, oy + Q_BASELINE * m), 'Q', font=font, fill=CREAM, anchor='ms')
    return img.resize((size, size), Image.LANCZOS)


if __name__ == '__main__':
    vector('ic_quapp_mark.xml', full_mark_paths(), 40, 50, comment='The Quapp ticket mark.')

    # Adaptive icon: 108dp canvas, 66dp safe zone. The mark is 46dp wide, centred.
    s = 1.15
    tx, ty = round((108 - W * s) / 2, 2), round((108 - H * s) / 2, 2)
    vector('ic_launcher_foreground.xml', group(full_mark_paths('        '), s, tx, ty), 108, 108, 108, 108,
           comment='Launcher icon foreground: the mark on the paper background colour.')
    vector('ic_launcher_monochrome.xml', group(cutout_path('        ', '#FF000000'), s, tx, ty), 108, 108, 108, 108,
           comment='Themed launcher icon (Android 13+): one colour, tinted by the system.')

    # Notification small icon: 24dp, one colour (the system tints it), the mark 22dp tall.
    s = 0.44
    vector('ic_stat_quapp.xml', group(cutout_path('        '), s, round((24 - W * s) / 2, 2), 1), 24, 24, 24, 24,
           comment='Notification small icon: the ticket with the Q punched through.')

    for folder, px in [('mdpi', 48), ('hdpi', 72), ('xhdpi', 96), ('xxhdpi', 144), ('xxxhdpi', 192)]:
        out = os.path.join(RES, f'mipmap-{folder}')
        raster(px, False).save(os.path.join(out, 'ic_launcher.webp'), 'WEBP', lossless=True)
        raster(px, True).save(os.path.join(out, 'ic_launcher_round.webp'), 'WEBP', lossless=True)
    print('logo assets written')
